# Checking if the server is running
# Maybe we can later directly pass a pdf file to the server

POST https://localhost:8083/pdf_to_markdown/
Content-Type: application/json

{
    "pdf_bytes": "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    "api_model": "gpt-4o-mini",
    "api_url": "https://api.openai.com/v1",
    "api_key": "sk-proj-1234567890"
}
